---
sudo: required

services:
  - docker

install:
  - gem install awesome_bot

script:
  # Link Checks
  - awesome_bot --white-list "$" --allow-dupe --allow-redirect --skip-save-results `find . -name "*.md"`

