dist: xenial

node_js:
  - "8"

addons:
  apt:
    packages:
    - jq
    - npm

install:
  # Install ansible and ansible-lint
  - sudo pip install ansible ansible-lint

  # Install markdownlint and markdown-link-check
  - sudo -E npm install -g markdownlint-cli markdown-link-check > /dev/null

script:
  - set -e

  # Markdown check
  - |
    echo '"line-length": false' > markdownlint_config.json
    markdownlint -c markdownlint_config.json README.md

  # Link Checks
  - |
    echo '{ "ignorePatterns": [ { "pattern": "^(http|https)://localhost" } ] }' > config.json
    markdown-link-check --config config.json README.md

  # Validate Packer templates
  - |
    PACKER_LATEST_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/packer | jq -r -M '.current_version')
    curl -s https://releases.hashicorp.com/packer/${PACKER_LATEST_VERSION}/packer_${PACKER_LATEST_VERSION}_linux_amd64.zip --output /tmp/packer_linux_amd64.zip
    sudo unzip -o /tmp/packer_linux_amd64.zip -d /usr/local/bin/
    for FILE in *.json; do
      echo "*** $FILE"
      RUN=$(cat $FILE | jq -r '."_comment" | join("; ")' | sed 's/packer build/packer validate/g;')
      echo "* $RUN"
      eval "$RUN"
    done

  # Check the boxes at app.vagrantup.com
  - |
    for VAGRANT_PROVIDER in virtualbox libvirt; do
      for NAME in ubuntu-{18.10,18.04}-desktop-amd64 ubuntu-{18.04,16.04,14.04}-server-amd64 my_ubuntu-{18.04,16.04}-server-amd64 my_centos-7-x86_64 my_windows-10-enterprise-x64-eval windows-{server-{{2016,2012_r2}-standard,2019-datacenter},10-enterprise}-x64-eval; do
        CURRENT_VERSION=$(curl -s https://app.vagrantup.com/api/v1/box/peru/$NAME | jq -r ".current_version.version")
        URL="https://app.vagrantup.com/peru/boxes/$NAME/versions/$CURRENT_VERSION/providers/$VAGRANT_PROVIDER.box"
        echo "*** $URL"
        curl -L --fail --silent --head --output /dev/null "$URL" || ( echo "* Failed... ^^^" && exit 1 )
      done
    done

  # Check Ansible playbooks
  - ansible-playbook -i 'localhost,' --syntax-check ansible/*.yml
  - ansible-lint -x 204,403 ansible/*.yml
