sudo: required

env:
  - PACKER_URL=https://releases.hashicorp.com/packer/1.2.3/packer_1.2.3_linux_amd64.zip

# Install jq
addons:
  apt:
    packages:
    - jq

install:
  - gem install awesome_bot
  - sudo pip install ansible

script:
  # Remove all iso links form *.md files
  - find . -name "*.md" -exec sed -i '/.*\.iso/d' {} \;
  # Link Checks
  - awesome_bot --white-list "$" --allow-dupe --allow-redirect --skip-save-results `find . -name "*.md"`
  # Validate Packer templates
  - |
    for FILE in *.json; do
      echo "*** $FILE"
      RUN=$(cat $FILE | jq -r '."_comment" | join("; ")' | sed 's/packer build/packer validate/g;')
      eval "$RUN"
    done
  # Check Ansible playbooks
  - ansible-playbook -i 'localhost,' --syntax-check ansible/*.yml
