---
# This can be used only with latest Ubuntu
- hosts: all
  gather_facts: false

  vars:
    build_path: /var/tmp/

    packages:
      - curl
      - git
      - jq
      - libvirt-bin
      - libvirt-dev
      - python3-pip
      - sshpass
      - tigervnc-viewer
      - unzip
      - virtualbox-6.1
      - wget

    grafana_admin_password: grafana_admin_password
    builder_username: builder

    vagrant_plugins:
      - vagrant-libvirt

    action_runner_count: 2

  pre_tasks:
    - name: Install python3-minimal and gnupg2 if needed
      raw: sudo bash -c "test -x /usr/bin/python3 || ( apt -qq update && apt install -y gnupg2 python3-minimal )"
      register: output
      changed_when: output.stdout is search("Unpacking")

    - name: Gather facts
      setup:

  roles:
    - role: ansible-role-my_common_defaults
      become: true
    - role: cloudalchemy.node-exporter
      node_exporter_enabled_collectors:
        - diskstats:
            ignored-devices: "^(ram|loop|fd)\\d+$"
        - filesystem:
            ignored-mount-points: "^/(dev|proc|run|sys)($|/)"
            ignored-fs-types: "^(sys|proc|auto)fs$"
        - interrupts
        - meminfo_numa
        - mountstats
        - netstat:
            fields: "(.*)"
        - systemd
        - tcpstat
        - vmstat:
            fields: "(.*)"

    - role: cloudalchemy.prometheus
      prometheus_storage_retention: "40d"
      prometheus_targets:
        node:
          - targets:
              - localhost:9100
        grafana:
          - targets:
              - "localhost:3000"
      prometheus_scrape_configs:
        - job_name: "prometheus"
          metrics_path: "/metrics"
          static_configs:
            - targets:
                - "localhost:9090"
        - job_name: "node"
          file_sd_configs:
            - files:
                - "/etc/prometheus/file_sd/node.yml"
        - job_name: "grafana"
          file_sd_configs:
            - files:
                - "/etc/prometheus/file_sd/grafana.yml"

    - role: cloudalchemy.grafana
      grafana_security:
        admin_user: admin
        admin_password: "{{ grafana_admin_password }}"
      grafana_auth:
        anonymous:
          org_name: "Main Org."
          org_role: Viewer
      grafana_datasources:
        - name: "Prometheus"
          type: "prometheus"
          access: "proxy"
          url: "http://127.0.0.1:9090"
          isDefault: true
      grafana_dashboards:
        - dashboard_id: '1860'
          revision_id: '12'
          datasource: '{{ grafana_datasources.0.name }}'
        - dashboard_id: '3662'
          revision_id: '2'
          datasource: '{{ grafana_datasources.0.name }}'
        - dashboard_id: '9852'
          revision_id: '1'
          datasource: '{{ grafana_datasources.0.name }}'

  tasks:
    - block:
        - name: Update all packages to the latest version
          apt:
            upgrade: dist
            update_cache: yes
          register: result
          until: result is succeeded

        - name: Get latest version of Vagrant
          uri:
            url: https://checkpoint-api.hashicorp.com/v1/check/vagrant
            return_content: yes
          register: vagrant_uri

        - name: Install Vagrant
          apt:
            deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_uri.json.current_version }}/vagrant_{{ vagrant_uri.json.current_version }}_{{ ansible_architecture }}.deb"
          register: result
          until: result is succeeded

        - name: Add an Apt signing key for Virtualbox
          apt_key:
            url: "{{ item }}"
          loop:
            - https://www.virtualbox.org/download/oracle_vbox_2016.asc
            - https://www.virtualbox.org/download/oracle_vbox.asc

        - name: Add Virtualbox repository
          apt_repository:
            repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib

        - name: Install packages
          apt:
            name: "{{ item }}"
          loop: "{{ packages }}"
          register: result
          until: result is succeeded

        - name: Install latest Ansible and pywinrm
          pip:
            name:
              - ansible
              - pywinrm
          register: result
          until: result is succeeded

        - name: Add the actions-runner user to docker and libvirt group
          user:
            name: "{{ builder_username }}"
            groups: docker,kvm,libvirt,vboxusers
            append: yes

        # This is not needed for Fedora, because in Fedora it's "crw-rw-rw- 1 root kvm 10, 232 Feb 13 09:58 /dev/kvm"
        - name: Chnage righs for /dev/kvm
          blockinfile:
            path: /etc/udev/rules.d/60-qemu-system-common.rules
            create: yes
            block: |
              # Chnaging rights of /dev/kvm from 0660 to 0666
              KERNEL=="kvm", GROUP="kvm", MODE="0666"
          notify: reboot

        - name: Get latest version of Packer
          uri:
            url: https://checkpoint-api.hashicorp.com/v1/check/packer
            return_content: yes
          register: packer_uri

        - name: Download and unzip packer
          unarchive:
            src: "https://releases.hashicorp.com/packer/{{ packer_uri.json.current_version }}/packer_{{ packer_uri.json.current_version }}_linux_amd64.zip"
            dest: /usr/local/bin/
            remote_src: yes
            creates: /usr/local/bin/packerio
            validate_certs: false

        - name: Move packer to packerio
          command: mv /usr/local/bin/packer /usr/local/bin/packerio
          args:
            creates: /usr/local/bin/packerio

        - name: Remove configuration of unix socket for libvirt (/var/run/libvirt/libvirt-sock)
          replace:
            path: /etc/libvirt/libvirtd.conf
            # Commend all lines beginning with "unix_sock_"
            regexp: '^unix_sock_.*'
            replace: '#&'
            backup: yes
          notify: reboot

      become: true

    - block:
        - name: List installed Vagrant Plugins
          command: vagrant plugin list
          register: vagrant_plugin_list
          changed_when: false

        - name: Install Vagrant Plugins
          command: vagrant plugin install {{ item }}
          loop: "{{ vagrant_plugins }}"
          when: vagrant_plugin_list.stdout is not search(item)

        - name: Create a directories for action-runners if they do not exist
          file:
            path: /home/{{ builder_username }}/actions-runner-{{ item }}
            state: directory
          loop: "{{ range(1, action_runner_count + 1) | list }}"

        - name: Get latest "actions-runner" release
          uri:
            url: "https://api.github.com/repos/actions/runner/releases/latest"
          register: github_api_action_runner

        - name: Download and unpack the "actions-runner"
          unarchive:
            src: https://github.com/actions/runner/releases/download/v{{ github_api_action_runner.json.tag_name[1:] }}/actions-runner-linux-x64-{{ github_api_action_runner.json.tag_name[1:] }}.tar.gz
            dest: /home/{{ builder_username }}/actions-runner-{{ item }}
            remote_src: yes
          loop: "{{ range(1, action_runner_count + 1) | list }}"

        - name: Register actions-runner-x
          command: ./config.sh --url {{ MY_PACKER_TEMPLATES_GITHUB_REPOSITORY }} --token {{ GITHUB_SELF_HOSTED_RUNNER_TOKEN }} --agent "{{ ansible_hostname }}-{{ item }}" --work "_work"
          args:
            chdir: /home/{{ builder_username }}/actions-runner-{{ item }}
            creates: /home/{{ builder_username }}/actions-runner-{{ item }}/.runner
          loop: "{{ range(1, action_runner_count + 1) | list }}"

      become: yes
      become_user: "{{ builder_username }}"

    - name: Install actions-runner-x service
      shell: ./svc.sh install && ./svc.sh start
      become: true
      args:
        chdir: /home/{{ builder_username }}/actions-runner-{{ item }}
        creates: /home/{{ builder_username }}/actions-runner-{{ item }}/.service
      environment:
        SUDO_USER: "{{ builder_username }}"
      loop: "{{ range(1, action_runner_count + 1) | list }}"

  handlers:
    - name: reboot
      become: true
      reboot:
