---
# This can be used only with latest Ubuntu
- hosts: all
  gather_facts: false

  vars:
    build_path: /var/tmp/

    packages:
      - curl
      - docker.io
      - git
      - gitlab-runner
      - jq
      - libvirt-bin
      - libvirt-dev
      - python3-pip
      - unzip
      - virtualbox-6.0
      - wget
    packer_templates_git_repo: https://github.com/ruzickap/packer-templates.git

    vagrant_plugins:
      - vagrant-libvirt

  tasks:
    - name: Install Python
      raw: sudo bash -x -c "test -x /usr/bin/python3 || ( apt -qq update && apt install -y python3-minimal )"
      register: output
      changed_when: output.stdout is search("Unpacking")

    - name: Gather facts
      setup:

    - block:
      - name: Update all packages to the latest version
        apt:
          upgrade: dist
          update_cache: yes
        register: result
        until: result is succeeded

      - name: Get latest version of Vagrant
        uri:
          url: https://checkpoint-api.hashicorp.com/v1/check/vagrant
          return_content: yes
        register: vagrant_uri

      - name: Install Vagrant
        apt:
          deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_uri.json.current_version }}/vagrant_{{ vagrant_uri.json.current_version }}_{{ ansible_architecture }}.deb"
        register: result
        until: result is succeeded

      - name: Add an Apt signing key for Virtualbox
        apt_key:
          url: "{{ item }}"
        loop:
          - https://www.virtualbox.org/download/oracle_vbox_2016.asc
          - https://www.virtualbox.org/download/oracle_vbox.asc

      - name: Add Virtualbox repository
        apt_repository:
          repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib

      - name: Download GitLab's official repository script
        get_url:
          url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
          dest: /root/script.deb.sh
          mode: 0755

      - name: Install GitLab's official repository
        command: /root/script.deb.sh
        args:
          creates: /etc/apt/sources.list.d/runner_gitlab-runner.list

      - name: Install packages
        apt:
          name: "{{ item }}"
        loop: "{{ packages }}"
        register: result
        until: result is succeeded

      - name: Install latest Ansible and pywinrm
        pip:
          name:
            - ansible
            - pywinrm
        register: result
        until: result is succeeded

      - name: Add the gitlab-runner user to docker and libvirt group
        user:
          name: gitlab-runner
          groups: docker,kvm,libvirt,vboxusers
          append: yes

      # Yhis is not needed for Fedora, because in Fedora it's "crw-rw-rw- 1 root kvm 10, 232 Feb 13 09:58 /dev/kvm"
      - name: Chnage righs for /dev/kvm
        blockinfile:
          path: /etc/udev/rules.d/60-qemu-system-common.rules
          create: yes
          block: |
            # Chnaging rights of /dev/kvm from 0660 to 0666
            KERNEL=="kvm", GROUP="kvm", MODE="0666"
        notify: reboot

      - name: Get latest version of Packer
        uri:
          url: https://checkpoint-api.hashicorp.com/v1/check/packer
          return_content: yes
        register: packer_uri

      - name: Download and unzip packer
        unarchive:
          src: "https://releases.hashicorp.com/packer/{{ packer_uri.json.current_version }}/packer_{{ packer_uri.json.current_version }}_linux_amd64.zip"
          dest: /usr/local/bin/
          remote_src: yes
          creates: /usr/local/bin/packerio
          validate_certs: false

      - name: Move packer to packerio
        command: mv /usr/local/bin/packer /usr/local/bin/packerio
        args:
          creates: /usr/local/bin/packerio

      - name: Remove configuration of unix socket for libvirt (/var/run/libvirt/libvirt-sock)
        replace:
          path: /etc/libvirt/libvirtd.conf
          # Commend all lines beginning with "unix_sock_"
          regexp: '^unix_sock_.*'
          replace: '#&'
          backup: yes
        notify: reboot

      - name: Check if gitlab-runner is already registered
        command: gitlab-runner list
        register: gitlab_runner_list
        changed_when: false

      - name: Register gitlab agent
        command: gitlab-runner register --non-interactive --tag-list packer-templates --registration-token {{ GITLAB_REGISTRATION_TOKEN }} --url https://gitlab.com/ --executor shell
        when: GITLAB_REGISTRATION_TOKEN is defined and gitlab_runner_list.stderr is not search('https://gitlab.com/')

      become: true

    - block:
      - name: List installed Vagrant Plugins
        command: vagrant plugin list
        register: vagrant_plugin_list
        changed_when: false

      - name: Install Vagrant Plugins
        command: vagrant plugin install {{ item }}
        loop: "{{ vagrant_plugins }}"
        when: vagrant_plugin_list.stdout is not search(item)

      become: yes
      become_user: gitlab-runner


  handlers:
    - name: reboot
      become: true
      reboot:
