---
- hosts: all

  vars:
    bleachbit_url: https://download.bleachbit.org/BleachBit-2.0-portable.zip

  roles:
    - role: ansible-role-virtio-win
      virtio_win_iso_path: 'E:\\'
      when: ansible_system_vendor == "QEMU"

  tasks:
    - name: Enable Remote Desktop
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        value: fDenyTSConnections
        data: 0
        datatype: dword

    - name: Allow connections from computers running any version of Remote Desktop (less secure)
      win_regedit:
        key: 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
        value: UserAuthentication
        data: 0
        datatype: dword

    - name: Allow RDP traffic
      win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable Administrator account
      win_user:
        name: Administrator
        account_disabled: no
      when: ansible_distribution is search("Microsoft Windows 10")

    - name: Remove all current pagefiles
      win_pagefile:
        remove_all: yes
        automatic: no
        state: absent

    - name: Disable Hibernate Mode
      win_command: powercfg -h off
      changed_when: false
      when: ansible_distribution is search("Microsoft Windows 10")

    - name: Download BleachBit
      win_get_url:
        url: "{{ bleachbit_url }}"
        dest: "%HOMEDRIVE%\\BleachBit-portable.zip"

    - name: Unzip downloaded BleachBit
      win_unzip:
        src: "%HOMEDRIVE%\\BleachBit-portable.zip"
        dest: "%HOMEDRIVE%\\"
        delete_archive: yes

    - name: Get latest UltraDefrag url
      win_uri:
        url: https://sourceforge.net/projects/ultradefrag/rss?path=/stable-release
        return_content: yes
      register: ultradefrag_url_output

    - name: Set UltraDefrag url
      set_fact:
        ultradefrag_url: "{{ ultradefrag_url_output.content |  regex_search('<link>(.*ultradefrag-portable.*amd64.zip.*)</link>','\\1') | first }}"

    - name: Download UltraDefrag from {{ ultradefrag_url }}
      win_get_url:
        url: "{{ ultradefrag_url }}"
        dest: "%HOMEDRIVE%\\ultradefrag-portable.bin.amd64.zip"

    - name: Unzip downloaded Ultra Defrag
      win_unzip:
        src: "%HOMEDRIVE%\\ultradefrag-portable.bin.amd64.zip"
        dest: "%HOMEDRIVE%\\"
        delete_archive: yes

    - name: Install windows updates
      win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
      ignore_errors: yes
