name: checks

on:
  push:
    branches: [master]
    paths:
    - '**.md'
    - '*.json'
    - '.github/**'
    - 'ansible/**'
    - .spelling
    - package-lock.json
    - package.json

jobs:
  markdown-lint-check:
    name: Markdown lint and spell check
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Install markdown-spellcheck
      run: npm install -g markdown-spellcheck

    - name: Create markdownlint configuration file
      run: |
        echo "{ MD013: { code_blocks: false } }" > /tmp/markdownlint_config.json

    - name: Run markdownlint
      run: find . -path ./node_modules -prune -o -name "*.md" -print0 | xargs -t -0 markdownlint -c /tmp/markdownlint_config.json

    - name: Run mdspell
      run: mdspell '**/*.md' '!**/node_modules/**/*.md' --ignore-numbers --ignore-acronyms --report --en-gb

  validate-packer-templates:
    name: Validate Packer templates
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Download Packer
      run: |
        PACKER_LATEST_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/packer | jq -r -M '.current_version')
        curl -s https://releases.hashicorp.com/packer/${PACKER_LATEST_VERSION}/packer_${PACKER_LATEST_VERSION}_linux_amd64.zip --output /tmp/packer_linux_amd64.zip
        sudo unzip -o /tmp/packer_linux_amd64.zip -d /usr/local/bin/

    - name: Check packer templates
      run: |
        IFS=$'\n'
        for FILE in *.json; do
          echo "*** $FILE"
          for PACKER_VALIDATE_RUN in $(awk -F\" '/"_comment"/ { gsub("packer build","packer validate",$4); print $4 }' $FILE); do
            echo "* $PACKER_VALIDATE_RUN"
            eval "$PACKER_VALIDATE_RUN"
          done
        done

  check-ansible-playbooks:
    name: Verify Ansible playbooks
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install ansible and ansible-lint
      run: |
        sudo pip install ansible ansible-lint

    - name: Test Ansible plabooks
      run: |
        ansible-playbook -i 'localhost,' --syntax-check ansible/*.yml
        ansible-lint -x 204,403 ansible/*.yml
